# Generated by Django 5.0.2 on 2024-03-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('valor', models.FloatField(max_length=15)),
                ('lista_medidas', models.CharField(max_length=100)),
            ],
        ),
    ]
